name: Release

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
      id-token: write

    environment: release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Set up Ruby
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
      with:
        bundler-cache: true
        ruby-version: 4.0.6
    - name: Configure trusted publishing credentials
      uses: rubygems/configure-rubygems-credentials@dc5a8d8553e6ee01fc26761a49e99e733d17954a # v2.1.0
    - name: Run release rake task
      run: bundle exec rake release
      shell: bash
    - name: Wait for release to propagate
      run: gem exec rubygems-await pkg/*.gem
      shell: bash
