name: RuboCop

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

    - name: Set up Ruby 3.4
      uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1
      with:
        ruby-version: 3.4
        bundler-cache: true

    - name: Run RuboCop
      run: bundle exec rubocop --parallel
